theme: minima
title: Just a practice
author: GitHub User
email: liu.huan@whu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  This is just a practice for me to fully understand how github work.

# social links
twitter_username: Badgerliu # DO NOT include the @ character, or else the build will fail!
github_username:  Badgerliu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
